#!/bin/bash

source config.sh
source account.sh

CMD="domain_update"

FILE=$1

if [ ! -f $FILE ]; then
    echo "File ${FILE} not found!"
    exit
fi

while read DOMAIN; do
	if [ "$DOMAIN" ]; then
	     	echo "Domain: $DOMAIN"
		curl "${URL}/${CMD}/?nichdl=${NIC}&token=${API_KEY}&domain=${DOMAIN}&ns1=${NS1}&ns2=${NS2}"
		echo "\n"
		sleep 0.25
	fi
done < $FILE


